STRATEGY:
  MODULE: 'long_ema_crossover'
  NAME: 'LongEMAcrossOver'
  INTERVAL: '1h'
  PERIOD: 300
  RISK_PC: 90
  SIZING: 'risk'
  PARAMETERS:
    slow_ema: 20
    fast_ema: 10
    RR: 1

# Define pairs to monitor
WATCHLIST: ['AAPL']