NAME: 'Portfolio Rebalance'
MODULE: 'portfolio_rebalance'
CLASS: 'Rebalance'
INTERVAL: '1h'
PERIOD: 300
INCLUDE_BROKER: True
PARAMETERS:
  rebalance_interval: 'weekly' # Not sure how this will be handled yet
  rebalance_percentages:
    VAS.AX: 40 # %
    VGS.AX: 40 # %
    VGB.AX: 20 # %

WATCHLIST: ['VAS.AX',
            'VGS.AX',
            'VGB.AX']