NAME: 'SuperTrend Scanner'
MODULE: 'alt_supertrend'
CLASS: 'SuperTrendScan'
INTERVAL: '1h'
PERIOD: 300
RISK_PC: 1.5
SIZING: 'risk'
PARAMETERS:
  candle_tol: 5

WATCHLIST: ['EURUSD=X',
            'AUDCAD=X',
            'EURJPY=X',
            'EURAUD=X',
            'AUDJPY=X']
            